version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.8-browsers  # Use an appropriate Java version
    working_directory: ~/project
    steps:
      - checkout  # Check out your code from your VCS (e.g., GitHub)
      - run:
          name: Install Dependencies
          command: mvn clean install -DskipTests  # Install dependencies without running tests

      # You can add more steps here as needed, such as running database migrations, etc.

      - run:
          name: Run Tests
          command: mvn test  # Run your Maven tests
